// Boneyard bones registry
// Auto-generated by `npx boneyard-js build`
// Manual entries below serve as fallbacks until CLI capture runs

import { registerBones } from "boneyard-js/svelte";

registerBones("hero-kicker", {
	375: [{ x: 16, y: 8, width: 200, height: 16, rx: 2 }],
	768: [{ x: 32, y: 16, width: 280, height: 18, rx: 2 }],
	1280: [{ x: 32, y: 16, width: 320, height: 18, rx: 2 }],
});

registerBones("hero-name", {
	375: [{ x: 16, y: 36, width: 280, height: 56, rx: 4 }],
	768: [{ x: 32, y: 48, width: 500, height: 72, rx: 4 }],
	1280: [{ x: 32, y: 48, width: 600, height: 80, rx: 4 }],
});

registerBones("hero-tagline", {
	375: [{ x: 16, y: 100, width: 260, height: 14, rx: 2 }],
	768: [{ x: 32, y: 132, width: 380, height: 16, rx: 2 }],
	1280: [{ x: 32, y: 140, width: 440, height: 18, rx: 2 }],
});

registerBones("hire-work-card", {
	375: [
		{ x: 12, y: 12, width: 0, height: 140, rx: 2 },
		{ x: 12, y: 160, width: 120, height: 12, rx: 2 },
	],
	768: [
		{ x: 16, y: 16, width: 0, height: 180, rx: 2 },
		{ x: 16, y: 204, width: 140, height: 14, rx: 2 },
	],
	1280: [
		{ x: 16, y: 16, width: 0, height: 200, rx: 2 },
		{ x: 16, y: 224, width: 160, height: 14, rx: 2 },
	],
});

registerBones("hire-pillar", {
	375: [{ x: 16, y: 8, width: 180, height: 14, rx: 2 }, { x: 16, y: 28, width: 280, height: 40, rx: 2 }],
	768: [{ x: 16, y: 12, width: 220, height: 16, rx: 2 }, { x: 16, y: 36, width: 500, height: 48, rx: 2 }],
	1280: [{ x: 16, y: 12, width: 260, height: 16, rx: 2 }, { x: 16, y: 36, width: 600, height: 48, rx: 2 }],
});

registerBones("hire-role", {
	375: [{ x: 16, y: 4, width: 200, height: 14, rx: 2 }, { x: 16, y: 22, width: 160, height: 10, rx: 2 }],
	768: [{ x: 16, y: 4, width: 260, height: 16, rx: 2 }, { x: 16, y: 26, width: 200, height: 12, rx: 2 }],
	1280: [{ x: 16, y: 4, width: 300, height: 16, rx: 2 }, { x: 16, y: 26, width: 240, height: 12, rx: 2 }],
});