// Hand-rolled shortcode → emoji map. ~110 popular entries, < 4KB minified.
// Symmetric to utils/emojiUtils.ts (which goes the other direction for the
// UTF-code display toggle). Backdrop-only substitution: the underlying
// content string is never mutated.
export const EMOJI_SHORTCODES: Map<string, string> = new Map([
  // Faces — happy
  ["smile", "😀"],
  ["grinning", "😀"],
  ["grin", "😁"],
  ["joy", "😂"],
  ["rofl", "🤣"],
  ["smiley", "😃"],
  ["sweat_smile", "😅"],
  ["laughing", "😆"],
  ["wink", "😉"],
  ["blush", "😊"],
  ["yum", "😋"],
  ["sunglasses", "😎"],
  ["heart_eyes", "😍"],
  ["kissing_heart", "😘"],
  ["star_struck", "🤩"],
  ["partying_face", "🥳"],

  // Faces — neutral / negative
  ["neutral_face", "😐"],
  ["expressionless", "😑"],
  ["thinking", "🤔"],
  ["face_with_raised_eyebrow", "🤨"],
  ["smirk", "😏"],
  ["unamused", "😒"],
  ["roll_eyes", "🙄"],
  ["pensive", "😔"],
  ["sleepy", "😪"],
  ["sleeping", "😴"],
  ["yawning_face", "🥱"],
  ["pleading_face", "🥺"],
  ["cry", "😢"],
  ["sob", "😭"],
  ["scream", "😱"],
  ["fearful", "😨"],
  ["worried", "😟"],
  ["confused", "😕"],
  ["tired_face", "😫"],
  ["weary", "😩"],
  ["triumph", "😤"],
  ["angry", "😠"],
  ["rage", "😡"],
  ["face_with_symbols_on_mouth", "🤬"],
  ["exploding_head", "🤯"],
  ["hot_face", "🥵"],
  ["cold_face", "🥶"],
  ["nauseated_face", "🤢"],
  ["face_vomiting", "🤮"],
  ["mask", "😷"],

  // Hands & gestures
  ["wave", "👋"],
  ["raised_hand", "✋"],
  ["ok_hand", "👌"],
  ["pinching_hand", "🤏"],
  ["v", "✌️"],
  ["crossed_fingers", "🤞"],
  ["love_you_gesture", "🤟"],
  ["metal", "🤘"],
  ["call_me_hand", "🤙"],
  ["point_left", "👈"],
  ["point_right", "👉"],
  ["point_up", "☝️"],
  ["point_down", "👇"],
  ["thumbsup", "👍"],
  ["+1", "👍"],
  ["thumbsdown", "👎"],
  ["-1", "👎"],
  ["fist", "✊"],
  ["punch", "👊"],
  ["clap", "👏"],
  ["raised_hands", "🙌"],
  ["pray", "🙏"],
  ["handshake", "🤝"],
  ["muscle", "💪"],

  // Hearts & symbols
  ["heart", "❤️"],
  ["orange_heart", "🧡"],
  ["yellow_heart", "💛"],
  ["green_heart", "💚"],
  ["blue_heart", "💙"],
  ["purple_heart", "💜"],
  ["black_heart", "🖤"],
  ["white_heart", "🤍"],
  ["broken_heart", "💔"],
  ["sparkling_heart", "💖"],
  ["two_hearts", "💕"],
  ["sparkles", "✨"],
  ["star", "⭐"],
  ["star2", "🌟"],
  ["fire", "🔥"],
  ["boom", "💥"],
  ["dizzy", "💫"],
  ["zap", "⚡"],
  ["100", "💯"],
  ["check", "✅"],
  ["white_check_mark", "✅"],
  ["x", "❌"],
  ["warning", "⚠️"],
  ["question", "❓"],
  ["exclamation", "❗"],
  ["bangbang", "‼️"],

  // Weather & nature
  ["sun", "☀️"],
  ["sunny", "☀️"],
  ["cloud", "☁️"],
  ["partly_sunny", "⛅"],
  ["rain_cloud", "🌧️"],
  ["snowflake", "❄️"],
  ["snowman", "⛄"],
  ["umbrella", "☂️"],
  ["rainbow", "🌈"],
  ["moon", "🌙"],
  ["earth_americas", "🌎"],
  ["earth_africa", "🌍"],
  ["earth_asia", "🌏"],

  // Food & drink
  ["coffee", "☕"],
  ["tea", "🍵"],
  ["beer", "🍺"],
  ["wine_glass", "🍷"],
  ["pizza", "🍕"],
  ["hamburger", "🍔"],
  ["taco", "🌮"],
  ["cake", "🍰"],
  ["birthday", "🎂"],
  ["cookie", "🍪"],
  ["apple", "🍎"],

  // Objects
  ["rocket", "🚀"],
  ["bulb", "💡"],
  ["bell", "🔔"],
  ["lock", "🔒"],
  ["key", "🔑"],
  ["computer", "💻"],
  ["phone", "📱"],
  ["camera", "📷"],
  ["headphones", "🎧"],
  ["book", "📖"],
  ["pencil", "✏️"],
  ["memo", "📝"],
  ["calendar", "📅"],
  ["clock", "🕐"],
  ["hourglass", "⌛"],
  ["trophy", "🏆"],
  ["medal", "🏅"],
  ["gift", "🎁"],
  ["balloon", "🎈"],
  ["tada", "🎉"],
  ["confetti_ball", "🎊"],

  // Animals
  ["dog", "🐶"],
  ["cat", "🐱"],
  ["mouse", "🐭"],
  ["rabbit", "🐰"],
  ["fox", "🦊"],
  ["bear", "🐻"],
  ["panda_face", "🐼"],
  ["unicorn", "🦄"],
  ["bee", "🐝"],
  ["butterfly", "🦋"],
  ["whale", "🐳"],
  ["dolphin", "🐬"],
  ["fish", "🐟"],
  ["octopus", "🐙"],

  // People & abstract
  ["eyes", "👀"],
  ["brain", "🧠"],
  ["bone", "🦴"],
  ["skull", "💀"],
  ["ghost", "👻"],
  ["alien", "👽"],
  ["robot", "🤖"],
  ["poop", "💩"],
]);

const SHORTCODE_PATTERN = /:([a-zA-Z0-9_+-]+):/g;

/**
 * Substitute known `:shortcode:` tokens in `text` with their emoji glyphs.
 * Unknown shortcodes are left verbatim. The input string is never mutated;
 * a new string is returned.
 */
export function replaceShortcodesWithEmoji(text: string): string {
  if (!text || text.indexOf(":") === -1) return text;
  return text.replace(SHORTCODE_PATTERN, (match, name: string) => {
    const emoji = EMOJI_SHORTCODES.get(name.toLowerCase());
    return emoji ?? match;
  });
}
